// Data constants for the DfE Digital Standards 2030 Self-Assessment Tool.
// Loaded first — has no DOM dependencies.

// ─── Standards data ───────────────────────────────────────────────────────────
const SRC = {
  broadband:  "https://www.gov.uk/guidance/meeting-digital-and-technology-standards-in-schools-and-colleges/broadband-internet-core-standard",
  cyber:      "https://www.gov.uk/guidance/meeting-digital-and-technology-standards-in-schools-and-colleges/cyber-security-core-standard",
  leadership: "https://www.gov.uk/guidance/meeting-digital-and-technology-standards-in-schools-and-colleges/digital-leadership-and-governance-core-standard",
  filtering:  "https://www.gov.uk/guidance/meeting-digital-and-technology-standards-in-schools-and-colleges/filtering-and-monitoring-core-standard",
  switching:  "https://www.gov.uk/guidance/meeting-digital-and-technology-standards-in-schools-and-colleges/network-switching-core-standard",
  wireless:   "https://www.gov.uk/guidance/meeting-digital-and-technology-standards-in-schools-and-colleges/wireless-network-core-standard",
};

const STANDARDS = [
  { id:"broadband", name:"Broadband Internet", short:"Broadband", icon:"⚡", color:"#2563eb",
    desc:"Full fibre broadband with resilience, appropriate speeds and safeguarding systems in place.",
    questions:[
      {id:"b1",type:"dfe",text:"Is your school connected via a full fibre connection — either a leased line or FTTP — meeting DfE minimum speeds?",
       opts:["No full fibre connection — copper, ADSL or connection type unknown","Partial or hybrid fibre — not yet full fibre to the premises","Full fibre in place but below DfE minimum speeds for your school type","Full fibre connection meeting DfE minimum speeds — primary 100Mbps↓/30Mbps↑ or secondary 1Gbps↓↑"],
       tips:["DfE states copper connections do not meet the standard. Full fibre (leased line or FTTP) is required. Investigate availability with your provider.","Partial fibre does not meet the standard. DfE requires a full fibre connection — FTTP or a leased line. Plan to upgrade at your next contract renewal.","Full fibre is in place — check speeds meet DfE minimums: 100Mbps down / 30Mbps up for primary, 1Gbps down/up for secondary schools and colleges.","Meets the DfE broadband core standard. Full fibre with correct speeds. Review at contract renewal to ensure speeds keep pace with demand."],
       actions:["Contact your ISP to request a site survey for full fibre (leased line or FTTP) availability. Use the DfE \'Compare broadband types\' tool. Check eligibility for Connect the Classroom funding at get-help-buying-for-schools.service.gov.uk.","Begin contract review process — ensure any renewal includes a clause to switch to full fibre when available. Check speeds against DfE minimums: 100Mbps↓/30Mbps↑ for primary, 1Gbps↓↑ for secondary."],example:"e.g. Virgin Media / BT leased line, Openreach FTTP, Glide, Timico, Exponential-e"},
      {id:"b2",type:"dfe",text:"Do you have a secondary broadband connection of a different type for automatic failover if your primary connection fails?",
       opts:["No backup connection — a single broadband failure would take the school offline","Backup connection being planned but not yet implemented","Backup connection in place but failover requires manual intervention","Backup connection of a different service type with fully automatic failover and redundant power on core equipment"],
       tips:["DfE requires a backup broadband connection to maintain continuity. A single connection is a critical single point of failure.","Planning is a positive step. DfE expects resilient services to be implemented as soon as possible after a primary connection is installed.","A backup connection reduces risk but DfE requires automatic failover — manual switching causes unacceptable downtime.","Best practice: multiple connection types (e.g. leased line + FTTP or FTTP + satellite), automatic failover and redundant power meets the DfE resilience standard fully."],
       actions:["Contact your provider to discuss adding a backup connection of a different service type (e.g. FTTP + satellite or leased line + FTTP). Configure multiple routers for automatic failover. Add redundant power to core network equipment.","Test and document your failover process. Ensure it is automatic rather than manual. Check that redundant power (UPS) is in place on core active network equipment."],example:"e.g. Primary leased line + 4G/5G failover; secondary dual leased lines from different providers with auto-failover router"},
      {id:"b3",type:"dfe",text:"Are you running dual routers configured for automatic WAN failover — so if one connection drops, traffic switches over without manual intervention?",
       opts:["No router resilience — single router only, no failover capability","Some resilience in place but failover is not automatic or has not been tested","Multiple routers configured for failover but not fully tested or documented","Multiple routers with automatic failover — configured, tested and documented"],
       tips:["DfE requires multiple routers with appropriate configuration for automatic failover. A single router cannot meet the resilience standard.","Basic failover capability is a starting point but DfE requires testing and documentation to evidence the standard is met.","Multiple routers are in place — DfE expects failover to be tested regularly and outcomes documented to evidence compliance.","Best practice: multiple routers with tested, documented automatic failover configuration meets the DfE broadband resilience standard."],
       actions:["Engage your provider or IT support to configure multiple routers with automatic failover. Document the failover process with named contacts and test it. A tabletop exercise is sufficient initially.","Schedule an annual failover test and document the outcome. Ensure the process is automatic, not manual, with named responsibility for monitoring alerts."],example:"e.g. Dual Cisco/Meraki routers with automatic WAN failover, or pfSense dual WAN configured and tested"},
      {id:"b4",type:"dfe",text:"Do you have a content filtering solution and boundary firewall in place that meets KCSIE requirements (paragraphs 123–135), formally reviewed with your DSL?",
       opts:["No content filtering or boundary firewall in place","Basic filtering in place but does not fully meet KCSIE requirements — no formal firewall review","Filtering and firewall in place but not formally reviewed against KCSIE paragraphs 123–135 with the DSL","Filtering meets KCSIE paragraphs 123–135, boundary firewall in place — both formally reviewed and documented with the DSL"],
       tips:["DfE requires filtering and a firewall as part of the broadband standard. Schools are expected to already meet KCSIE safeguarding requirements.","Partial filtering does not meet KCSIE requirements. Review against paragraphs 123–135 of KCSIE and implement an appropriate firewall.","Filtering and firewall are in place — DfE expects these to be formally reviewed against KCSIE 123–135. Document your review process.","Best practice: filtering meeting KCSIE 123–135 with a documented firewall review meets the DfE broadband safeguarding and security standard."],
       actions:["Review your current filtering against KCSIE paragraphs 123-135 with your DSL. Engage your IT support to confirm a correctly configured firewall is in place on the boundary. Use the UKSIC filtering checklist at saferinternet.org.uk.","Document your filtering review against KCSIE 123-135 and schedule annual formal review with DSL involvement. Confirm your firewall covers all external connections."],example:"e.g. Smoothwall, Lightspeed, Fortinet with KCSIE-compliant profiles; boundary firewall such as Cisco ASA, Fortinet or pfSense"},
    ]},
  { id:"cyber", name:"Cyber Security", short:"Cyber Security", icon:"🔐", color:"#dc2626", ofsted:true,
    desc:"Keep your school or college cyber secure and control and secure user accounts.",
    questions:[
      {id:"c1",type:"dfe",text:"Do you complete a formal cyber risk assessment every year, with a termly review involving your SLT digital lead, IT support and DPO — with outcomes logged in your risk register?",
       opts:["No cyber risk assessment in place","Risk assessment completed but not reviewed termly, or not all key stakeholders involved","Annual risk assessment in place with some termly review, but not all required stakeholders consistently involved","Formal annual cyber risk assessment reviewed every term — SLT digital lead, IT support and DPO all involved, outcomes logged in risk register"],
       tips:["DfE requires a cyber risk assessment to be conducted annually and reviewed every term. Without it, you cannot identify or mitigate risks.","The DfE standard requires termly review involving the SLT digital lead, IT support and data protection officer (DPO).","Good progress — DfE expects all three parties (SLT, IT support, DPO) to be involved and outcomes to be captured in a risk register.","Best practice: annual assessment reviewed every term with SLT, IT support and DPO involvement, outcomes in the risk register — meets the DfE standard fully."],
       actions:["Conduct a cyber risk assessment immediately involving SLT digital lead, IT support and DPO. Use the NCSC Exercise in a Box tool (ncsc.gov.uk) for a free structured starting point. Capture outcomes in your risk register.","Formalise termly review with SLT, IT support and DPO. Set calendar reminders. Ensure outcomes are recorded and fed into the risk register. Consider using NCSC\'s Cyber Assessment Framework as a structure."],example:"e.g. NCSC Cyber Assessment Framework (CAF), NCSC Exercise in a Box for termly simulation, outcomes logged in risk register"},
      {id:"c2",type:"dfe",text:"Do you have an Acceptable Use Policy signed by all staff and students, backed by a documented annual cyber awareness training programme with completion records and governor sign-off?",
       opts:["No acceptable use policy or structured cyber awareness training in place","AUP exists but training is ad hoc, not documented, and not all staff have signed the AUP","AUP signed by all staff with some structured training — but completion not recorded for all staff or not reviewed annually","AUP in place with governor sign-off, regular documented training for all staff and students, completion records reviewed annually"],
       tips:["DfE requires a cyber awareness plan including an acceptable use policy signed by all users, including supply staff and guests.","Ad hoc training is insufficient. DfE expects regular, up-to-date training and awareness activities covering all staff and students.","Good progress — DfE requires the AUP to be approved by governors and training completion to be recorded for all users.","Best practice: AUP with governor approval, documented training for all staff and students meets the DfE cyber awareness standard."],
       actions:["Create an acceptable use policy using a template from NCSC or your local authority. Ensure all staff, supply teachers and guests sign it. Deliver initial awareness training — NCSC\'s free \'Top Tips for Staff\' e-learning is a good starting point.","Roll out AUP to all remaining staff and ensure governor sign-off. Implement documented training with completion records — consider free NCSC e-learning or your MAT\'s training platform."],example:"e.g. KnowBe4, Proofpoint Security Awareness Training, NCSC free staff e-learning, annual all-staff training day"},
      {id:"c3",type:"dfe",text:"Is MFA enforced — not just enabled — for all SLT and staff with access to confidential, financial or personal data, including all privileged and admin accounts?",
       opts:["MFA not in place for any accounts","MFA available but optional, or only applied to some admin accounts","MFA enforced for email and cloud services but not all accounts handling sensitive, financial or personal data","MFA enforced for all SLT, all staff handling confidential, financial or personal data, and all privileged and admin accounts"],
       tips:["DfE requires MFA for senior leaders and all staff working with confidential, financial and personal/sensitive personal data.","Optional MFA does not meet the DfE standard. It must be enforced, not optional, for the specified user groups.","Good — extend MFA to all accounts handling sensitive data and all privileged/admin accounts to fully meet the DfE requirement.","Best practice: MFA enforced for all required user groups as specified in the DfE cyber security standard."],
       actions:["Enable and enforce MFA immediately for all SLT and staff handling confidential, financial or personal data. For Microsoft 365 use Entra ID Conditional Access. For Google Workspace use 2-Step Verification enforcement in Admin Console.","Extend MFA enforcement to all privileged and admin accounts. Review Conditional Access policies to ensure there are no bypass routes. Document exceptions with risk justification."],example:"e.g. Microsoft Entra ID Conditional Access policies, Google Workspace 2-Step Verification enforcement in Admin Console"},
      {id:"c4",type:"dfe",text:"Do you have a cyber response plan sitting within your BCM, tested annually with a simulation exercise, stored in both hard copy and a secure cloud location with named roles documented?",
       opts:["No cyber response plan or business continuity plan exists","A plan or draft exists but is not formally part of BCM and has not been tested","Cyber response plan exists within BCM and has been distributed to named staff — but not yet tested with a simulation exercise","Cyber response plan within BCM, tested annually with a simulation exercise, stored in both hard copy and a secure cloud location — named roles documented and staff briefed"],
       tips:["DfE requires a cyber response plan as part of your business continuity plan. It is also a condition of cover under DfE Risk Protection Arrangement (RPA).","An untested plan is unlikely to work under pressure. DfE requires annual testing with simulations such as data loss or hardware failure.","DfE requires the plan to be tested annually, distributed to named staff, and stored in at least two locations (hard copy and cloud).","Best practice: tested cyber response plan within BCM, stored in hard copy and cloud, with named roles — meets DfE standard and RPA conditions."],
       actions:["Create a cyber response plan as a standalone document or within your BCM. Include named contacts, definition of a \'disaster\', and response steps. Store in hard copy and a secure cloud folder. Check DfE RPA conditions at gov.uk/guidance/the-risk-protection-arrangement-rpa-for-schools.","Schedule an annual test of the cyber response plan — a tabletop exercise simulating ransomware or data loss is sufficient. Document gaps identified and actions taken. Share the plan summary with all staff."],example:"e.g. Annual tabletop exercise simulating ransomware; plan stored in SharePoint and printed copy in server room"},
      {id:"c5",type:"dfe",text:"Do you have a complete asset register, with all devices licensed, supported and covered by automated vulnerability fixes — including software patches, firmware updates and configuration changes — alongside endpoint anti-malware and a correctly configured boundary firewall?",
       opts:["Assets unknown or unlicensed — no anti-malware or firewall in place","Some assets documented, partial anti-malware coverage, no formal vulnerability fix schedule","Asset register in place, most devices covered by anti-malware and automated patching — firewall present but not all vulnerability fixes confirmed","Full asset register, all devices licensed and supported, automated vulnerability fixes covering software patches, firmware updates and configuration changes, anti-malware and correctly configured firewall on all systems"],
       tips:["DfE requires all digital technology to be licensed, supported and kept up to date. Vulnerability fixes include software patches, firmware updates and configuration changes — not just software alone. Anti-malware and a correctly configured firewall are required.","Partial coverage creates gaps. DfE requires anti-malware on all devices, a firewall protecting all external connections, and vulnerability fixes applied across software, firmware and device configuration.","Good progress — DfE requires a complete asset register and automated vulnerability fixes with checks, not just scheduled manual software updates. Ensure firmware and configuration hardening are included.","Best practice: full asset register, automated vulnerability fixes covering software, firmware and configuration, anti-malware and configured firewall on all systems fully meets the DfE cyber security standard."],
       actions:["Audit all devices for licensing and support status. Implement anti-malware on all devices — Windows Defender is built-in and free. Configure Windows Update or Intune/JAMF for automated patching. Ensure firmware updates are applied automatically where possible. Ensure firewall is correctly configured on the boundary.","Enable automated vulnerability fix delivery across all managed devices — covering software patches, firmware updates and configuration changes. Use Intune, JAMF, SCCM or equivalent to track compliance. Schedule monthly manual checks and document results. Replace any unlicensed or unsupported software."],example:"e.g. Microsoft Intune or SCCM for automated patching and firmware updates, Windows Defender or Sophos/CrowdStrike for endpoint protection, Lansweeper for asset register"}
    ]},
  { id:"leadership", name:"Digital Leadership & Governance", short:"Leadership", icon:"🏛️", color:"#7c3aed",
    desc:"Effective digital technology leadership, governance, roles, responsibilities and processes.",
    questions:[
      {id:"l1",type:"dfe",text:"Do you have a named SLT member formally assigned as your digital lead, and a named link governor for digital technology on your governing body?",
       opts:["No named SLT digital lead or governor digital link role in place","Responsibility exists informally but not formally assigned or documented","Named SLT digital lead assigned — no named governor digital link role","Named SLT digital lead with documented remit and a named governor digital link role formally in place"],
       tips:["DfE requires the headteacher/principal to assign an SLT member as digital lead before a digital strategy can be created.","Informal responsibility does not meet the standard. The SLT digital lead must be formally assigned with clear accountability.","Good — DfE also recommends governors assign a digital link role within the governing body or board of trustees.","Best practice: named SLT digital lead with documented remit and a named governor digital link role meets the DfE leadership standard."],
       actions:["Headteacher should formally assign an SLT member as digital lead with a written remit. Governors should identify a digital link governor. Use NCSC\'s School Governor Questions resource to brief them on responsibilities.","Document the SLT digital lead\'s remit covering strategy, budget, standards compliance and safeguarding oversight. Identify a governor digital link. Both roles should be in the meeting schedule."],example:"e.g. Deputy Head as named SLT digital lead; named link governor for digital in governing body terms of reference"},
      {id:"l2",type:"dfe",text:"Do you maintain up-to-date contracts, asset and information asset registers covering all digital technology — reviewed ahead of each financial planning cycle and built using DfE templates?",
       opts:["No registers in place for digital technology assets, contracts or information","Partial registers — not all three types in place or significantly out of date","All three registers exist but not consistently maintained or reviewed ahead of financial planning","Contracts, asset and information asset registers all maintained, reviewed ahead of each financial planning cycle — using DfE templates"],
       tips:["DfE requires three registers: a contracts register, asset register and information asset register covering all digital technology.","Partial registers create blind spots. All three must be in place and kept up to date — DfE provides templates for each.","All three registers are in place — DfE expects them to be reviewed ahead of each financial planning cycle and kept current.","Best practice: all three registers maintained using DfE templates and reviewed before financial planning fully meets this standard."],
       actions:["Create a contracts register using the DfE template at plan-technology-for-your-school.education.gov.uk. Create an asset register and information asset register (IAR) — DfE templates are available for all three. Review before your next financial planning cycle.","Ensure all three registers are actively maintained: update at every asset change, and review ahead of each financial planning cycle. Assign IT support to update technical fields and the DPO to maintain the IAR."],example:"e.g. DfE asset register template, Lansweeper or Snipe-IT for hardware, contracts spreadsheet with renewal dates and supplier contacts"},
      {id:"l3",type:"dfe",text:"Is your digital technology covered in a documented disaster recovery and BCM plan — tested annually, stored in both hard copy and cloud, and distributed to named staff?",
       opts:["No disaster recovery or business continuity plan exists for digital technology","BCM plan exists but digital technology is not included, or it has never been tested","Digital technology included in BCM and reviewed — but not tested annually or not widely distributed","Digital technology fully included in BCM, tested annually, stored in hard copy and secure cloud location, distributed to all named staff"],
       tips:["DfE requires digital technology to be within disaster recovery and business continuity plans. Insurance providers may ask for these documents.","Digital technology must be explicitly included — a general BCM without it does not meet the DfE standard.","DfE requires the disaster recovery plan to be tested annually (at minimum), not just reviewed, with gaps identified and actioned.","Best practice: digital technology in BCM, tested annually, stored in hard copy and cloud, distributed to named staff meets the DfE standard."],
       actions:["Include digital technology in your disaster recovery and business continuity plan. Use the DfE\'s digital technology BCM guidance. Test the plan with a tabletop exercise and store copies in both hard copy and a secure cloud location.","Schedule annual testing of the disaster recovery plan with a simulated incident. Ensure the digital technology section is updated after any significant change. Distribute a summary document to all named staff."],example:"e.g. DfE digital strategy template, 3-year rolling technology plan reviewed annually with SLT and governors"},
      {id:"l4",type:"dfe",text:"Do you have a digital strategy that's reviewed annually, built on your asset registers and BCM, and aligned to your School Development Plan — with SLT and governor involvement?",
       opts:["No digital technology strategy exists","Draft or partial strategy in place — not formally approved or aligned to the school development plan","Strategy exists and has been reviewed — but not within the last 12 months","Digital technology strategy reviewed annually, aligned to school development plan, informed by registers and BCM, formally approved by governors"],
       tips:["DfE requires a digital technology strategy. It should only be created after the SLT lead, registers and BCM are in place.","A draft or unapproved strategy does not meet the standard. DfE requires formal approval and annual review.","DfE expects the strategy to be reviewed every year. An outdated strategy cannot effectively guide buying decisions or risk management.","Best practice: annual strategy review aligned to the development plan, informed by registers and BCM, approved by governors meets the DfE standard."],
       actions:["Complete the first three standards (SLT lead, registers, BCM) before building your strategy. Use the DfE\'s \'Plan Technology for Your School\' service to self-assess and structure your strategy around your development plan.","Schedule an annual strategy review aligned to the school development plan. Ensure the strategy is informed by your registers and BCM, addresses all 6 core standards, and is approved by governors."],example:"e.g. DfE disaster recovery template, BCM plan stored in SharePoint and server room, tested annually via tabletop exercise"},
      {id:"l5",type:"dfe",text:"Are all relevant staff aware of the digital strategy, and do you have a process to identify and action technology training needs for both staff and students?",
       opts:["Strategy not shared — staff are unaware of the school's digital technology direction","Strategy shared with SLT only — not embedded across the wider school","Strategy communicated to most staff — digital training needs not yet formally identified","Strategy shared with all relevant staff, digital training needs identified and included in the strategy, reviewed annually"],
       tips:["DfE states the SLT digital lead is responsible for encouraging use of digital technology and identifying training needs for staff and students.","The strategy should drive staff engagement — DfE expects it to be communicated and embedded, not just a leadership document.","Good — DfE requires training needs for both staff and students to be formally identified and actioned as part of the strategy.","Best practice: strategy embedded across the school with training needs identified and actioned annually meets the DfE governance standard."],
       actions:["Share the digital technology strategy with all relevant staff. Identify training needs for both staff and students — include these in the strategy. Use the DfE EdTech Demonstrator Programme for peer support.","Build staff training needs into the annual strategy review. Record what training has been completed and what is planned. Ensure the strategy is communicated to curriculum leads and pastoral staff, not just IT."],example:"e.g. Annual staff technology survey via Microsoft Forms, CPD plan linked to digital strategy, curriculum leads involved in training needs review"},
    ]},
  { id:"filtering", name:"Filtering & Monitoring", short:"Filtering", icon:"🛡️", color:"#d97706", ofsted:true,
    desc:"Provide a safe online environment with appropriate filtering and monitoring. Schools should already be meeting this standard now.",
    questions:[
      {id:"f1",type:"dfe", text:"Do you have all four key roles formally assigned and documented for filtering and monitoring — SLT lead, responsible governor, DSL and IT support — each with clear written responsibilities?",
        opts:["No named roles exist — filtering and monitoring responsibilities are unclear","Some roles informally assigned but not documented — governors not formally involved","Named SLT, DSL and IT support roles exist — but no formal responsible governor role assigned","All four roles formally assigned with documented responsibilities: SLT lead, responsible governor, DSL and IT support"],
        tips:["Governors and proprietors have overall strategic responsibility — not just awareness","The DSL must lead on safeguarding, check reports, respond to concerns and provide governor assurance","IT support has technical responsibility for maintaining systems, providing reports and completing actions"],
        actions:["Formally assign all four roles and document responsibilities in writing — who checks reports, who responds to concerns, who maintains systems, who provides governor assurance. Publish in safeguarding and online safety policies.","Ensure the DSL's filtering responsibilities are in their job description aligned to KCSIE. Brief the responsible governor. Confirm IT support has received safeguarding and online safety training."],example:"e.g. DSL = SENCO or Pastoral Lead; SLT lead = Deputy Head; responsible governor named in safeguarding and online safety policy"},
      {id:"f2",type:"dfe", text:"Do you carry out a formal annual filtering and monitoring review involving all four roles — SLT, DSL, IT support and responsible governor — covering student risk profiles, generative AI tools like ChatGPT and Copilot, and BYOD? Is it also triggered by key events like new technology, safeguarding incidents or network changes?",
        opts:["No formal review of filtering and monitoring takes place","Annual review occurs but only involves IT support — DSL and governors not involved","Annual review involves SLT, DSL, IT support and the responsible governor — but does not yet consider student risk profiles, generative AI or event-based triggers","Comprehensive annual review involves all four roles, considers student risk profiles, generative AI tools and BYOD — also triggered by new technology, BYOD changes or identified safeguarding risks"],
        tips:["The 2025 update explicitly requires generative AI tools to be considered in the annual review","Student risk profiles must consider: age, SEND, EAL, county lines, digital resilience, and RSHE/PSHE curriculum needs","The review must also be triggered by: new safeguarding risks, changes to BYOD/remote access, new devices, major software updates, or network configuration changes — not just annually"],
        actions:["Schedule your annual review with SLT, DSL, IT support and the responsible governor. Agenda must cover: student risk profiles, generative AI tool usage, BYOD for staff and students, outside safeguarding influences, and current filtering effectiveness. Use the UKSIC review framework at saferinternet.org.uk. Record outcomes and make available for inspection.","Establish event-based triggers for an unscheduled review: identified safeguarding risk, BYOD/remote changes, new devices, major software updates, or network changes. Ensure the review informs: policies, training, curriculum, monitoring strategies and procurement decisions."],example:"e.g. Annual review agenda includes: generative AI tools (ChatGPT, Copilot), BYOD policy, student risk profiles by year group and vulnerability"},
      {id:"f3",type:"dfe", text:"Does your filtering solution have IWF and CTIRU blocklists active and confirmed they cannot be disabled at any level, separate profiles for staff, students and guests, VPN/proxy blocking enabled, safe search locked, and all connections filtered — including backup connections, portable WiFi and BYOD on a separate virtual network?",
        opts:["IWF/CTIRU blocklists not confirmed active or can be disabled — no separate filtering profiles exist","Blocklists active but not confirmed that they cannot be disabled — separate user profiles not in place","Blocklists confirmed active and cannot be disabled, separate staff and student profiles in place — but VPN/proxy blocking, safe search locking or BYOD filtering not all fully confirmed","Full compliance: IWF/CTIRU blocklists active and cannot be disabled, separate student/staff/guest profiles, VPN/proxy bypass blocked, safe search locked, all connections filtered including backups and portable WiFi, BYOD on a separate virtual network"],
        tips:["Blocklists must not be disableable by anyone — including system administrators — at any level","VPNs, proxy services and end-to-end encryption bypass methods must be blocked at system level","Safe search must be locked — users must not be able to change browser or install unauthorised plugins","Filtering must cover ALL internet feeds including backup connections and portable WiFi — confirm with your provider","BYOD must be on a separate virtual network; mobile/app content must be filtered or technically monitored"],
        actions:["Confirm with your filtering provider that IWF and CTIRU blocklists are active, cannot be disabled at any level, and regularly updated. Confirm VPN, proxy and encryption bypass blocking is active at system level. Test using SWGfL testfiltering.com for: illegal child abuse material, terrorist content, and adult content.","Configure separate profiles for students, staff and guests. Lock safe search in all school browsers. Put BYOD on a separate virtual network. Confirm filtering covers backup connections and portable WiFi. Check mobile/app content filtering — if not covered, apply a technical monitoring system to those devices."],example:"e.g. Smoothwall, Lightspeed Systems, Cisco Umbrella — IWF/CTIRU enabled, VPN/proxy blocking active, profiles set per user group"},
      {id:"f4",type:"dfe", text:"Does your monitoring system send at least weekly reports to your DSL, with immediate alerts for high-risk incidents? Are users notified at login that their device is monitored, and have you completed a DPIA for your monitoring solution?",
        opts:["No technical monitoring in place and no structured process for manual monitoring or DSL reporting","Some monitoring exists but no regular DSL reports and no immediate alert process for high-risk incidents","Weekly DSL reports and alerting in place — but users are not notified they are being monitored and no DPIA has been completed","Full monitoring: minimum weekly reports to DSL, immediate alerts for high-risk incidents, users notified at login, DPIA completed, monitoring covers off-site devices and mobile/app content"],
        tips:["The DfE standard requires minimum weekly monitoring reports and immediate alerts for high-risk incidents (malicious, technical or safeguarding in nature)","Users must be notified that their device is being monitored — typically at login — this is a DfE and GDPR requirement","A DPIA is a legal requirement under UK GDPR for any school using a technical monitoring system — not optional","Monitoring must cover off-site devices and mobile/app content where filtering does not apply"],
        actions:["Configure monitoring for minimum weekly DSL reports and immediate alerts for high-risk incidents. Document the incident handling process: who leads, what actions are taken, how outcomes are recorded. Ensure monitoring data identifies the individual, device and time of concern.","Complete a DPIA for your technical monitoring system (ICO template at ico.org.uk). Add a login notification that the device is being monitored. Ensure monitoring covers off-site devices and mobile/app content. Include monitoring procedures in your AUP and safeguarding/online safety policies."],example:"e.g. Smoothwall or Lightspeed weekly DSL reports, immediate Category 1 alerts via email/SMS, DPIA completed using ICO template"},
      {id:"f5",type:"dfe", text:"Do you carry out regular logged filtering checks covering all devices including those taken home, all sites, all user groups and all connections including backups — and do all staff know how and where to report filtering concerns?",
        opts:["No systematic checks and no clear staff reporting process for filtering or safeguarding concerns","Ad hoc checks occur but not logged — staff reporting process not consistently communicated","Regular logged checks occur — but do not cover all device types, all locations, all user groups or backup connections","Systematic logged checks cover all school-owned devices including those taken off-site, all sites, all user group accounts, all connections including backups — all staff know the reporting process"],
        tips:["Checks must cover school-owned devices taken home — not just on-site devices","All sites must be checked if the school is on multiple premises","All user group accounts (student, staff, guest) must confirm the correct content is being filtered for each group","Backup connections and portable WiFi must be checked — not just the primary connection","Staff must know to report: suspected unsuitable access, ability to access unsuitable material, teaching topics that may create unusual filtering activity, or bypass attempts via abbreviations and misspellings"],
        actions:["Establish a regular check schedule based on your school risk profile. Use SWGfL testfiltering.com for minimum checks. Log every check: date, who checked, what was tested, and resulting actions. Ensure checks cover all managed devices including those taken home, all sites, all user group accounts, and all connections including backups.","Communicate the staff reporting process regularly. Staff should know to report if they can access unsuitable material, are teaching sensitive topics, or notice bypass attempts. Add reporting routes to staff induction, AUP and staff intranet. Review check frequency annually as part of the filtering and monitoring review."],example:"e.g. Monthly SWGfL testfiltering.com checks logged in SharePoint; staff report concerns to DSL via CPOMS, MyConcern or direct email"}
    ]},

  { id:"switching", name:"Network Switching & Cabling", short:"Network", icon:"🔌", color:"#059669",
    desc:"Fast, reliable and secure network switches with central management, security features and resilient power.",
    questions:[
      {id:"n1",type:"dfe",text:"Do your switches deliver at least 1Gbps to every end device, with Multi-Gigabit uplinks (2.5G or 10G), IEEE PoE compliance and 802.3az energy-efficient ports?",
       opts:["Switch speeds, PoE compliance or specifications unknown — likely below standard","Some switches below 1Gbps to user devices, or uplinks do not meet multi-gigabit requirements","Most switches provide 1Gbps to devices with multi-gigabit uplinks — PoE compliance not fully confirmed across the estate","All switches provide minimum 1Gbps to all users, multi-gigabit uplinks for high-bandwidth equipment, IEEE PoE compliant and 802.3az energy efficient throughout"],
       tips:["DfE requires a minimum of 1Gbps connectivity to user devices. Switches must also support multi-gigabit ports for servers, APs and media devices.","Below-standard switches cannot support current device density. DfE expects an upgrade plan at next replacement opportunity.","Good — DfE also requires PoE switches to comply with IEEE 802.3af/at/bt and all switches to meet 802.3az energy efficiency.","Best practice: 1Gbps to users, multi-gigabit uplinks, IEEE PoE compliance and 802.3az energy efficiency meets the DfE switching standard."],
       actions:["Engage IT support or a specialist to audit current switch estate against DfE technical requirements: minimum 1Gbps to user devices, multi-gigabit uplinks, IEEE PoE compliance, 802.3az energy efficiency. Create a costed replacement plan.","Replace sub-standard switches in highest-priority areas (server room, core infrastructure) first. Use DfE/Crown Commercial buying frameworks at get-help-buying-for-schools.service.gov.uk for procurement."],example:"e.g. HPE Aruba 2930M with mGig ports, Cisco Catalyst 9200 with 10G uplinks, Juniper EX Series — all 802.3az energy efficient"},
      {id:"n2",type:"dfe",text:"Do you manage all your switches from a central platform with automatic firmware and security updates, covered by a minimum 5-year warranty?",
       opts:["No central management — switches configured individually, no formal warranty or support","Partial central management in place, basic warranty coverage, no automatic firmware or security updates","Central management in place with warranty — firmware and security updates are manual rather than automatic","Full central management with automatic firmware and security updates, covered by a minimum 5-year warranty including licences and manufacturer-approved admin training"],
       tips:["DfE requires a central management tool to configure, monitor and alert on all switches. Individual configuration cannot meet this standard.","DfE requires a minimum 5-year warranty and support arrangement including licences, software enhancements and firmware updates.","Good — DfE requires firmware updates to be set to automatic as soon as available, plus a manufacturer-approved admin training package.","Best practice: central management with 5-year warranty, automatic updates and approved training on-site meets the DfE switching standard."],
       actions:["Procure a central management platform with your next switch purchase — ensure it meets DfE requirements: 5-year warranty, licence/firmware coverage, automatic security updates, and on-site manufacturer-approved admin training.","Ensure firmware updates are set to automatic as soon as they are available. Complete manufacturer-approved admin training if not done. Add manual check schedule alongside automatic updates."],example:"e.g. HPE Aruba Central, Cisco DNA Centre / Catalyst Centre, Juniper Mist, Cisco Meraki Dashboard"},
      {id:"n3",type:"dfe",text:"Do you have network access control (NAC) in place with 802.1X authentication, VLANs segmented by user group, QoS configured, and all admin accounts individually named and documented?",
       opts:["No formal security configuration — default or unknown switch settings in use","Basic VLAN separation in place but no network access controls, authentication controls or documented admin accounts","VLANs and QoS configured, some access controls in place — admin accounts not fully documented or individually named","Network access controls, secure individual authentication, VLANs, QoS and all admin accounts individually documented and secured throughout"],
       tips:["DfE requires network access controls (NACs) and policy management to ensure authorised devices are securely authenticated.","VLANs alone are insufficient. DfE requires NACs, secure authentication for all devices and full documentation of admin accounts.","Good — DfE requires all admin accounts to be secure and fully documented, and software updates to be automatic.","Best practice: NACs, secure authentication, VLANs, QoS, automatic updates and documented admin accounts meets the DfE security standard."],
       actions:["Engage IT support to configure network access controls (NACs), VLANs, QoS and secure individual authentication on all switches. Document all admin accounts with access to configuration changes. Ensure updates are set to automatic.","Review and document all admin accounts on switching infrastructure. Ensure no shared admin credentials. Test NAC configuration to confirm unauthorised devices cannot access the network."],example:"e.g. Cisco ISE or Aruba ClearPass for NAC, 802.1X authentication, VLANs segmented for staff / students / IoT / management"},
      {id:"n4",type:"dfe",text:"Do your core switches have dual power supplies, dual management modules, dual connections to critical infrastructure such as servers and routers, and are they protected by a UPS?",
       opts:["Single power supply on core switches — no UPS, no redundant connections or management modules","UPS in place but core switches do not have redundant power supplies or dual management modules","UPS and redundant power supplies in place — dual connections to critical infrastructure or dual management modules not yet fully implemented","Core switches have 2 power supplies, 2 management modules, 2 connections to critical infrastructure — all connected to UPS"],
       tips:["DfE requires core switches to have at least 2 power supplies, 2 management modules and 2 connections to critical infrastructure.","UPS alone is insufficient. DfE requires redundant power supplies and dual management modules on all core switches.","Good progress — DfE requires all three elements: redundant power, dual management modules and dual connections to routers/servers.","Best practice: 2 power supplies, 2 management modules, 2 connections to critical infrastructure and UPS meets the DfE resilience standard."],
       actions:["Identify all core switches and engage IT support to install redundant power supplies and connect to UPS. Check each core switch has at least 2 power supplies, 2 management modules and 2 connections to critical infrastructure.","Test UPS by simulating a power failure and confirming core switches remain operational. Document the test outcome. Schedule annual UPS testing as part of your disaster recovery process."],example:"e.g. Cisco Catalyst 9500 with dual PSU and dual supervisor modules, APC Smart-UPS on core rack, dual fibre runs to servers"},
      {id:"n5",type:"dfe",text:"Where you stack switches, are you using dedicated stacking ports running at 40GbE — for example Cisco StackWise or HPE Aruba VSX/MCLAG — and do your comms room uplinks run at 2×10Gbps back to the core server room via diverse cable routes?",
       opts:["Stacking not in use, or specification unknown — uplink speeds not confirmed","Stacking in use but not using dedicated stacking ports or 40Gbps interconnects","Stacking uses dedicated ports and 40Gbps interconnects — hub room uplinks below 2×10Gbps or not taking diverse cable routes","Stacked switches use dedicated 40Gbps stacking ports, hub room uplinks run at minimum 2×10Gbps via diverse cable routes to core server room"],
       tips:["DfE requires stacked switches to use dedicated stacking ports supporting 40Gbps interconnects between each switch in the stack.","Non-dedicated or slower stacking ports create bottlenecks. DfE specifies dedicated stacking ports for high-speed inter-switch communication.","Good — DfE also requires hub room links back to the core server room to use a minimum of 2×10Gbps with links taking different routes.","Best practice: 40Gbps dedicated stacking ports and 2×10Gbps diverse hub room uplinks meets the DfE network switching specification."],
       actions:["Audit your switch stack configuration against DfE requirements: dedicated stacking ports, 40Gbps interconnects between stacked switches, and 2×10Gbps uplinks from hub rooms to the core server room via diverse cable routes.","Upgrade hub room uplinks to minimum 2×10Gbps if not already in place. Ensure uplink cables take physically diverse routes to avoid a single cable failure causing an outage. Document configuration."],example:"e.g. HPE Aruba VSX or MCLAG across core switches, Cisco StackWise-480 at 40GbE, 2×10G SFP+ uplinks from IDFs via diverse cable routes"},
    ]},
  { id:"wireless", name:"Wireless Network", short:"Wireless", icon:"📶", color:"#0891b2",
    desc:"Reliable, centrally managed Wi-Fi coverage across all teaching and learning spaces.",
    questions:[
      {id:"w1",type:"dfe",text:"Does your wireless network meet the needs of your staff and students — and are you working towards Wi-Fi 7 as part of your next refresh?",
       opts:["Wi-Fi 5 or older — causing performance issues with no upgrade plan in place","Wi-Fi 5 or older — still meeting current needs but an upgrade is planned at next refresh","Wi-Fi 6 deployed — meeting current needs with a documented path to Wi-Fi 6E or Wi-Fi 7","Wi-Fi 6E or Wi-Fi 7 deployed or actively planned — fully aligned with the DfE wireless standard"],
       tips:["DfE requires schools to upgrade their wireless network when it no longer meets their needs, working towards Wi-Fi 7 as the latest standard. Performance issues indicate the standard is not being met.","Wi-Fi 5 can still meet needs in some schools — the DfE standard is to upgrade when performance is insufficient, targeting Wi-Fi 6E or Wi-Fi 7 at next refresh.","Wi-Fi 6 is a solid platform. DfE guidance targets Wi-Fi 6E and Wi-Fi 7 — document your upgrade path for the next refresh cycle.","Best practice: Wi-Fi 6E or Wi-Fi 7 fully meets the DfE wireless network standard. Wi-Fi 7 (802.11be) is the latest standard approved by the Wi-Fi Alliance."],
       actions:["Assess your current wireless performance against the needs of staff and students. If performance is insufficient, plan an upgrade to Wi-Fi 6E or Wi-Fi 7 at your earliest opportunity. Use DfE/Crown Commercial frameworks for procurement. Check Connect the Classroom eligibility.","Plan migration to Wi-Fi 6E or Wi-Fi 7 at next contract renewal. Document your upgrade path and timeline. Use the DfE wireless standards page for specification guidance."],example:"e.g. Aruba AP-635 (Wi-Fi 6E), Cisco Catalyst 9136 (Wi-Fi 6E), Ruckus R760 (Wi-Fi 6E), Ubiquiti U7 Pro (Wi-Fi 7), Aruba AP-770 (Wi-Fi 7)"},
      {id:"w2",type:"dfe",text:"Do you have full wireless coverage across all teaching spaces, specialist rooms and external areas where devices are used — verified by a heat mapping survey?",
       opts:["Limited or no wireless coverage in teaching areas — significant dead spots affecting teaching and learning","Partial coverage with notable gaps in teaching or learning spaces — some areas cannot reliably connect","Good coverage across most teaching spaces with only minor gaps — external areas or some specialist rooms not yet fully covered","Full wireless coverage throughout all buildings and external areas where required — verified using a wireless heat mapping survey"],
       tips:["DfE requires a fully functional wireless signal in all areas where mobile devices are used. Limited coverage fails the standard.","Dead spots disrupt teaching and learning. DfE guidance recommends heat mapping to identify and resolve coverage gaps.","Good coverage with minor gaps — DfE expects full coverage including external areas where required. Plan to close remaining gaps.","Best practice: full coverage designed using wireless heat mapping meets the DfE standard for wireless signal coverage."],
       actions:["Commission a wireless heat mapping survey to identify coverage gaps across all buildings and external areas. Use results to determine access point placement. DfE requires one AP per classroom as a minimum guide, with higher-spec units in high-capacity areas.","Address remaining coverage gaps identified by heat mapping. Ensure external areas where devices are used are included in the coverage plan. Document planned and completed coverage improvements."],example:"e.g. Ekahau or iBwave heat mapping survey, minimum one AP per classroom, higher-density APs in halls and communal spaces"},
      {id:"w3",type:"dfe",text:"Do you use a centralised management platform to manage all your access points — including automatic firmware and security updates, load balancing and performance alerting?",
       opts:["No central management — access points configured individually with no performance monitoring","Partial or basic central management in place — no automatic firmware or security updates","Centrally managed with monitoring and alerting — security updates applied manually rather than automatically","Full central management with automatic security updates, active load balancing, performance alerting, scalability and manufacturer-approved admin training"],
       tips:["DfE requires a central management tool to configure, monitor and update access points. Individual configuration cannot meet this standard.","Partial management is insufficient. DfE requires automatic firmware/security updates as soon as they are available.","Good — add automatic security updates to fully meet the DfE requirement for central management of wireless networks.","Best practice: full central management with automatic security updates and load balancing meets the DfE wireless management standard."],
       actions:["Procure a central management platform with your next access point purchase. Ensure it includes: active signal management and load balancing, performance monitoring and alerting, automatic security/firmware updates, and scalability. Ensure your procurement includes a minimum 5-year manufacturer support contract covering firmware and security updates, and arrange manufacturer-approved admin training (e.g. HPE Aruba, Cisco, Ruckus or Ubiquiti certified training).","Configure automatic security update delivery on your central management platform. Add manual check schedule alongside automatic updates. Ensure your support contract is reviewed annually and covers all access points. If admin training has not been completed, schedule it as part of your next procurement or refresh."],example:"e.g. Aruba Central, Cisco Meraki Dashboard, Ruckus SmartZone, Ubiquiti UniFi Controller, Extreme ExtremeCloud IQ"},
      {id:"w4",type:"dfe",text:"Do you have VLANs, WPA3 and ACLs configured across all SSIDs, with separate networks for staff, students and guests, and MFA enforced on all wireless admin accounts?",
       opts:["No meaningful wireless security controls — open network or shared WPA2 key only","Basic SSID separation in place but no VLANs, WPA3 or formal guest access controls","VLANs in place with separate staff, student and guest SSIDs — WPA3 not yet deployed or ACLs not fully configured","VLANs, ACLs, WPA3 across all SSIDs, secure segregated guest access and MFA for all wireless admin accounts — all configured and documented"],
       tips:["DfE requires authorised devices to be individually authenticated. Open or shared-key networks do not meet the standard.","Basic separation reduces risk but DfE specifically requires VLANs, WPA3 and secure individual authentication.","Good progress — to fully meet the standard, implement WPA3, access control lists (ACLs) and MFA for all admin accounts.","Best practice: VLANs, ACLs, WPA3, secure guest access and MFA for privileged users fully meets the DfE wireless security standard."],
       actions:["Implement VLANs, ACLs and WPA3 authentication on your wireless network. Configure separate SSIDs for staff, students and guests. Enable MFA for all admin accounts with access to the wireless management system. Document all configuration.","Extend security configuration to include wireless intrusion protection (WIPS) where available. Confirm WPA3 is in use and WPA2 is being phased out. Ensure all admin accounts are individually named and documented."],example:"e.g. WPA3-Enterprise (802.1X) for staff, WPA3-Personal for students, isolated guest VLAN, Aruba or Meraki role-based access control"},
    ]}
];

const CORE_STANDARDS = STANDARDS; // all standards are now core

// Split max scores — DfE requirement questions only vs best practice
function getMaxDfE(std) { return std.questions.filter(q=>q.type==="dfe").length * 3; }
function getMaxPractice(std) { return std.questions.filter(q=>q.type==="practice").length * 3; }
const TOTAL_MAX_DFE      = CORE_STANDARDS.reduce((s,std)=>s+getMaxDfE(std), 0);
const TOTAL_MAX_PRACTICE = CORE_STANDARDS.reduce((s,std)=>s+getMaxPractice(std), 0);
const TOTAL_MAX          = TOTAL_MAX_DFE; // overall score = DfE only

function scoreAnswers(ans){
  return STANDARDS.map(s=>{
    // All questions total (for backwards compat)
    const total = s.questions.reduce((sum,q)=>sum+(ans[q.id]??0),0);
    // DfE requirement questions only
    const dfePts  = s.questions.filter(q=>q.type==="dfe").reduce((sum,q)=>sum+(ans[q.id]??0),0);
    const dfeMax  = getMaxDfE(s);
    const dfePct  = dfeMax > 0 ? dfePts/dfeMax : null;
    // Best practice questions only
    const pracPts = s.questions.filter(q=>q.type==="practice").reduce((sum,q)=>sum+(ans[q.id]??0),0);
    const pracMax = getMaxPractice(s);
    const pracPct = pracMax > 0 ? pracPts/pracMax : null;
    // RAG based on DfE score only (or overall if no DfE questions)
    const ragPct  = dfePct !== null ? dfePct : total/(s.questions.length*3);
    return {id:s.id, name:s.short, total, pct:ragPct, rag:rag(ragPct), color:s.color,
            dfePts, dfeMax, dfePct, pracPts, pracMax, pracPct};
  });
}

// ─── National benchmark data ──────────────────────────────────────────────────
const BENCHMARKS = {
  broadband:{ stats:[
    {label:"Schools with adequate broadband",value:"~72%",context:"72% of IT leads agreed their school has an adequate broadband connection (TiSS 2025). The remaining 28% are a key target for DfE investment.",direction:"warn"},
    {label:"Connect the Classroom 2025–2030",value:"£325m",context:"Government has committed £325m to bring schools up to WiFi and connectivity standard over the next 5 years.",direction:"info"},
    {label:"DfE recommended minimum",value:"100 Mbps per 100 users",context:"DfE recommends at least 100 Mbps per 100 users. Schools below this should prioritise upgrading via approved procurement routes.",direction:"info"},
  ]},
  cyber:{ stats:[
    {label:"Secondary schools identifying a breach (2024)",value:"60%",context:"60% of secondary schools identified a cyber breach or attack — higher than UK businesses overall (43%). Phishing accounts for 89% of attacks.",direction:"warn"},
    {label:"Primary schools with a cyber policy",value:"82%",context:"82% of primary and 81% of secondary schools have an established cyber security policy — but policy alone is insufficient without testing.",direction:"ok"},
    {label:"Schools testing incident response",value:"Low",context:"Despite high policy adoption, regular testing and exercising of incident response plans remains inconsistent across schools.",direction:"warn"},
  ]},
  leadership:{ stats:[
    {label:"Schools with a digital strategy",value:"~65%",context:"Around two thirds of schools report having a digital technology strategy in place (TiSS 2025). Many lack annual review.",direction:"warn"},
    {label:"Board-level digital governance",value:"Improving",context:"The Academy Trust Handbook 2025 now explicitly requires trusts to work towards all 6 core standards — raising governance expectations.",direction:"info"},
    {label:"Awareness of DfE 2030 standards",value:"Growing",context:"Awareness has increased since publication but many schools are still in early stages of implementing all 6 standards.",direction:"info"},
  ]},
  filtering:{ stats:[
    {label:"Schools reviewing filtering annually",value:"Not universal",context:"A significant proportion of schools review their filtering system less than annually — the DfE/UKSIC expects at least annual review with DSL involvement.",direction:"warn"},
    {label:"Overblocking — a known issue",value:"Common",context:"Overblocking by filtering systems is frequently cited as a barrier to technology use in classrooms (TiSS 2025, Figure 8.4).",direction:"info"},
    {label:"KCSIE-aligned monitoring",value:"Improving",context:"Adoption of activity monitoring aligned to KCSIE requirements has improved but is not yet universal, particularly in primary schools.",direction:"warn"},
  ]},
  switching:{ stats:[
    {label:"Unmanaged switches still in use",value:"Significant minority",context:"Unmanaged and consumer-grade network hardware remains in use across a significant minority of schools, particularly older buildings.",direction:"warn"},
    {label:"VLAN segmentation adoption",value:"Limited",context:"Network segmentation with VLANs is still limited in many schools — flat networks remain common, posing a cyber risk.",direction:"warn"},
    {label:"DfE Cat 6A cabling standard",value:"Updated Jan 2024",context:"DfE guidance updated in January 2024 recommends Cat 6A cabling for all new installations. Many schools still on older copper cabling.",direction:"info"},
  ]},
  wireless:{ stats:[
    {label:"Schools below DfE WiFi standard",value:"Many",context:"DfE's Connect the Classroom programme is actively funding schools below the WiFi standard — indicating the scale of the gap.",direction:"warn"},
    {label:"Centrally managed WiFi adoption",value:"Growing",context:"Uptake of centrally managed wireless (controller-based or cloud-managed) has increased significantly since 2021.",direction:"ok"},
    {label:"Wi-Fi 6 in schools",value:"Early stage",context:"DfE recommends Wi-Fi 6 for new installations. Most schools are still operating on Wi-Fi 5 (802.11ac) infrastructure.",direction:"info"},
  ]}
};

// ─── Governor Report ──────────────────────────────────────────────────────────
// ─── Governor Report ─────────────────────────────────────────────────────────
const GOV_PLAIN = {
  broadband: {
    meeting: "Your school has a full fibre broadband connection that meets the DfE speed requirements, with a backup connection in place to ensure lessons can continue if the main connection fails.",
    developing: "Your school is working towards the DfE broadband standard. There are gaps in your connection type, speed or resilience that need addressing before 2030.",
    attention: "Your school's internet connection does not currently meet the DfE standard. This may affect the reliability of online teaching tools and cloud services used by staff and pupils.",
    risk: "Without reliable broadband, teachers cannot use online learning tools effectively. A single internet connection with no backup means any outage stops teaching across the school.",
    govQ: "Is our internet connection full fibre, and do we have a backup connection in case of failure?"
  },
  cyber: {
    meeting: "Your school has strong cyber security practices in place, including regular risk assessments, staff training, multi-factor authentication and a tested incident response plan.",
    developing: "Your school has some cyber security measures in place but there are gaps. Key controls such as MFA, regular risk assessments or a tested response plan may not yet be fully in place.",
    attention: "Your school is at significant risk from cyber attack. Essential controls — including risk assessments, staff training and incident response planning — are not sufficiently in place.",
    risk: "Schools are the most targeted sector for cyber attacks. A successful ransomware attack can close a school for days or weeks, destroy data, breach safeguarding information and cost tens of thousands of pounds to recover from.",
    govQ: "Do we have a cyber response plan, and when was it last tested? Are all staff trained in cyber awareness?"
  },
  leadership: {
    meeting: "Your school has clear digital leadership with a named SLT lead, up-to-date technology registers, a business continuity plan covering digital systems, and an annual digital strategy.",
    developing: "Digital leadership is developing. Some governance structures are in place but key requirements — such as up-to-date registers, a disaster recovery plan or an annual strategy review — may be incomplete.",
    attention: "Digital governance is not yet in place. Without a named SLT lead, current registers and a digital strategy, the school cannot effectively plan or oversee its technology.",
    risk: "Without clear digital governance, technology spending is reactive, risks go unmanaged and the school cannot evidence compliance with DfE standards to Ofsted, insurers or the trust.",
    govQ: "Who is our named SLT digital lead? Do we have an up-to-date digital strategy reviewed in the last 12 months?"
  },
  filtering: {
    meeting: "Your school meets the statutory filtering and monitoring requirements. Systems are reviewed annually, roles are clearly assigned and the DSL has oversight of online activity.",
    developing: "Filtering and monitoring systems are in place but may not fully meet statutory requirements. Annual reviews, clear role assignment or DSL oversight may need strengthening.",
    attention: "Filtering and monitoring does not meet the statutory requirements set out in Keeping Children Safe in Education. This is a safeguarding compliance risk that requires immediate attention.",
    risk: "Schools have a statutory duty to protect pupils from harmful online content. Failure to meet filtering and monitoring standards is a KCSIE compliance failure and would be a significant concern in an Ofsted inspection.",
    govQ: "When did we last review our filtering and monitoring provision? Is our DSL receiving regular reports and acting on them?"
  },
  switching: {
    meeting: "Your school's network infrastructure meets the DfE standard, with managed switches providing fast and secure connections, central management and resilient power protection.",
    developing: "Your network infrastructure is partially compliant. Some elements — such as switch specifications, central management, security controls or UPS provision — need upgrading to meet the DfE standard.",
    attention: "Your school's network infrastructure does not meet the DfE standard. This affects the reliability and security of every device and service in the school.",
    risk: "Poor network infrastructure causes unreliable connectivity across the school, increases cyber risk through unpatched or unmanaged devices, and can cause extended outages during a power issue or cyber incident.",
    govQ: "Is our network switching infrastructure managed and up to date? Do we have a hardware refresh plan in place?"
  },
  wireless: {
    meeting: "Your school has a modern wireless network meeting the DfE standard, with full coverage, central management, appropriate security controls and current Wi-Fi hardware.",
    developing: "Your wireless network is partially compliant. Coverage gaps, older hardware, limited central management or insufficient security controls need addressing to meet the 2030 standard.",
    attention: "Your school's wireless network does not meet the DfE standard. Coverage, hardware generation, management capability or security controls are significantly below what is required.",
    risk: "Inadequate wireless infrastructure limits the use of technology in teaching, creates security vulnerabilities and may mean pupils and staff cannot reliably access online tools across the school.",
    govQ: "Does our wireless network provide reliable coverage across all teaching spaces? Is it centrally managed with appropriate security?"
  }
};